# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title for page'),
        ),
    ]
