# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 08:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblayout', '0008_auto_20160516_1038'),
        ('website', '0008_auto_20160516_1031'),
        ('news', '0003_remove_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additional_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Additional text'),
        ),
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Gallery', verbose_name='Gallery'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Short text'),
        ),
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weblayout.Template', verbose_name='Alternative template'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Main text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image_description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title of main image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt of main image'),
        ),
    ]
