# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_staticpage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='is_news',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='second_image',
        ),
    ]
