# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:13
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160516_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimageposition',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_directory_path, verbose_name='Large image'),
        ),
        migrations.AlterField(
            model_name='bannerimageposition',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_directory_path, verbose_name='Medium image'),
        ),
        migrations.AlterField(
            model_name='bannerimageposition',
            name='image_original',
            field=models.ImageField(upload_to=core.utils.image_directory_path, verbose_name='Original image'),
        ),
        migrations.AlterField(
            model_name='bannerimageposition',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_directory_path, verbose_name='Small image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_directory_path, verbose_name='First image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_directory_path, verbose_name='Second image'),
        ),
        migrations.AlterField(
            model_name='galleryimageposition',
            name='image_original',
            field=models.ImageField(upload_to=core.utils.image_directory_path, verbose_name='Original image'),
        ),
    ]
