# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0010_auto_20160803_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='category_description',
            field=models.CharField(default='<category> <company>', help_text='category desc', max_length=255,
                                   verbose_name='Description for category'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='category_keywords',
            field=models.CharField(default='<company>, <category>', help_text='category keywords', max_length=255,
                                   verbose_name='Keywords for category'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='category_title',
            field=models.CharField(default='<category> - <company>', help_text='category title', max_length=255,
                                   verbose_name='Title for category'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='product_description',
            field=models.CharField(default='<product> <category> <company>', help_text='product desc', max_length=255,
                                   verbose_name='Description for product'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='product_keywords',
            field=models.CharField(default='<product>, <company>, <category>', help_text='product keywords',
                                   max_length=255, verbose_name='Keywords for product'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='product_title',
            field=models.CharField(default='<category> <product> - <company>', help_text='product title',
                                   max_length=255, verbose_name='Title for product'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='static_page_description',
            field=models.CharField(default='<page_name> <company>', help_text='static', max_length=255,
                                   verbose_name='Description for static page'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='static_page_keywords',
            field=models.CharField(default='<company>, <page_name>', help_text='static keys', max_length=255,
                                   verbose_name='Keywords for static page'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='static_page_title',
            field=models.CharField(default='<page_name> - <company>', help_text='static title', max_length=255,
                                   verbose_name='Title for static page'),
        ),
    ]
