# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import webshopcart.models


class Migration(migrations.Migration):

    dependencies = [
        ('webshopcart', '0005_auto_20160430_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Is complete?'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='date_on_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='date_on_close',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='delivery',
            field=models.ForeignKey(default=webshopcart.models.get_default_delivery, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='webshop.DeliveryRule', verbose_name='Delivery rule'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='fixed_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Order price'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Is paid?'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='username',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='webshopcart.ProductCart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Quantity of products'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='price_correction',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='product', chained_model_field='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.ProductPriceCorrector', verbose_name='Price corrector'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Product', verbose_name='Product'),
        ),
    ]
