# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webshopcart', '0006_auto_20160511_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Shipping address'),
        ),
    ]
