# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblayout', '0002_auto_20160328_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
