# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 07:55
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('weblayout', '0005_auto_20160331_1216'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
