# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weblayout', '0006_auto_20160430_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Alternative name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weblayout.Menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='weblayout.MenuItem', verbose_name='Parent menu item'),
        ),
    ]
