# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblayout', '0007_auto_20160511_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='alternative_url',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Alternative url'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Image of menu item'),
        ),
    ]
