# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 08:40
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblayout', '0008_auto_20160516_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='alternative_url',
            field=core.fields.SlugWithSlashField(blank=True, max_length=255, null=True, verbose_name='Alternative url'),
        ),
    ]
