# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0014_auto_20160411_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of range')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='webshop.ProductParameter', verbose_name='Parameter')),
            ],
        ),
        migrations.AddField(
            model_name='productparameteravailablevalue',
            name='parameter_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_values', to='webshop.ParameterRange', verbose_name='Parameter range'),
        ),
    ]
