# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0015_auto_20160412_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterrange',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
