# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 12:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0016_parameterrange_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameteravailablevalue',
            name='parameter_range',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='product_parameter', chained_model_field='parameter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_values', to='webshop.ParameterRange', verbose_name='Parameter range'),
        ),
    ]
