# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 07:55
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0018_auto_20160412_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productimageposition',
            name='cropping_large',
            field=image_cropping.fields.ImageRatioField('image_original', '0x0', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping large'),
        ),
        migrations.AlterField(
            model_name='productimageposition',
            name='cropping_medium',
            field=image_cropping.fields.ImageRatioField('image_original', '0x0', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping medium'),
        ),
        migrations.AlterField(
            model_name='productimageposition',
            name='cropping_small',
            field=image_cropping.fields.ImageRatioField('image_original', '0x0', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping small'),
        ),
        migrations.AlterField(
            model_name='productpricecorrector',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
