# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webshop', '0019_auto_20160430_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('body', models.TextField()),
                ('score', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Score')),
                ('status', models.SmallIntegerField(choices=[(0, 'Requires moderation'), (1, 'Approved'), (2, 'Rejected')], default=0, verbose_name='Status')),
                ('date_created', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='webshop.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ratings and comments for product',
                'verbose_name_plural': 'Rating and comment for product',
            },
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
