# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 11:43
from __future__ import unicode_literals

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0020_auto_20160506_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=utils.fields.NullCharField(max_length=255, unique=True),
        ),
    ]
