# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0020_auto_20160505_1732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set([('product', 'user')]),
        ),
    ]
