# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0021_auto_20160506_1443'),
        ('webshop', '0021_auto_20160505_1739'),
    ]

    operations = [
    ]
