# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0026_auto_20160524_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productparameter',
            options={'ordering': ('category', 'weight'), 'verbose_name': 'Product Parameter', 'verbose_name_plural': 'Product Parameters'},
        ),
        migrations.AlterModelOptions(
            name='productparametervalue',
            options={'ordering': ('product__weight', 'product_parameter__weight', 'value__weight'), 'verbose_name': 'Product Parameter Value', 'verbose_name_plural': 'Product Parameter Values'},
        ),
    ]
