# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0027_auto_20160610_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Это новинка?'),
        ),
    ]
