# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0028_auto_20160610_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный товар'),
        ),
    ]
