# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:28
from __future__ import unicode_literals

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0029_auto_20160610_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=utils.fields.NullCharField(max_length=255, unique=True, verbose_name='Article'),
        ),
    ]
