# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0030_auto_20160613_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='It is hit?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0, help_text='More is good', verbose_name='Weight of product'),
        ),
        migrations.AlterField(
            model_name='productimageposition',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productparametervalue',
            name='product_parameter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='webshop.ProductParameter', verbose_name='Product Parameter'),
        ),
        migrations.AlterField(
            model_name='productparametervalue',
            name='value',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='product_parameter', chained_model_field='product_parameter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='webshop.ProductParameterAvailableValue', verbose_name='Value of parameter'),
        ),
    ]
