# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0033_auto_20160616_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Введіть теги по яким буде вестись пошук. Теги разділяються комами.', max_length=255, verbose_name='Tags'),
        ),
    ]
