# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0034_auto_20160616_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=256, unique=True, verbose_name='ISBN'),
        ),
    ]
