# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0035_auto_20160616_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='Value')),
                ('display_order', models.PositiveSmallIntegerField(default=1, help_text='Сортування йде від меншого до більшого, числа повинні бути більше нуля', verbose_name='Display order')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published?')),
            ],
            options={
                'ordering': ('display_order',),
                'verbose_name_plural': 'Words of fast search',
                'verbose_name': 'Word of fast search',
            },
        ),
    ]
