# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0036_fastsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastsearch',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Сортування йде від меншого до більшого, числа повинні бути більше нуля', verbose_name='Display order'),
        ),
    ]
