# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0038_producttreereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseries',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True, verbose_name='Slug'),
        ),
    ]
