# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import webshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0039_auto_20160822_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(default=webshop.models.get_default_provider, on_delete=django.db.models.deletion.CASCADE, to='webshop.Provider', verbose_name='Provider'),
        ),
    ]
