# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0040_auto_20160822_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'category', 'series')]),
        ),
    ]
