# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 08:53
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0041_auto_20160826_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=core.utils.image_directory_path, verbose_name='Image')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='authors',
            field=models.ManyToManyField(related_name='products', to='webshop.Author', verbose_name='Author'),
        ),
    ]
